// Exercise variant pool — canonical mapping from protocol variant ids
// (e.g. "heel_elevated_goblet_squat") to PlannedExercise building blocks.
//
// Rehab protocols reference variants by stable ids. The planner looks up
// each id here to get a display name, muscle groups, equipment, role, and
// default rep-scheme hints. Later phases can normalize these into the
// main EXERCISE_LIBRARY or a dedicated "rehab variant" table.
//
// Keep ids snake_case. Display names Title Case. Adding a new variant:
// add an entry here + reference it in one or more rehab protocols.

import type { MuscleGroup } from '../../types/plan'

export interface VariantSpec {
  id: string
  name: string
  primary_muscles: MuscleGroup[]
  secondary_muscles: MuscleGroup[]
  equipment: string[]
  role: 'main lift' | 'accessory' | 'isolation' | 'core' | 'rehab' | 'mobility' | 'cardio'
  library_id?: string           // link to EXERCISE_LIBRARY when a 1:1 match exists
  // Warmup ramping behaviour. Main compounds get 3 ramp sets, accessories 1,
  // rehab/mobility/core get 0. Planner reads this to emit warmup_sets arrays.
  ramp_style?: 'compound' | 'accessory' | 'none'
  default_rest_seconds: number
}

// Main lift variants — compound movements, often rehab-staged.
export const MAIN_VARIANTS: Record<string, VariantSpec> = {
  // ── Squat pattern ────────────────────────────────────────────────────
  heel_elevated_goblet_squat: {
    id: 'heel_elevated_goblet_squat',
    name: 'Heel-Elevated Goblet Squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core'],
    equipment: ['dumbbell', 'plates'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 150,
  },
  goblet_squat_light: {
    id: 'goblet_squat_light',
    name: 'Goblet Squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core'],
    equipment: ['dumbbell'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 120,
  },
  box_squat_high: {
    id: 'box_squat_high',
    name: 'High-Box Squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core'],
    equipment: ['barbell', 'box'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },
  split_squat_rear_foot_elevated_bodyweight: {
    id: 'split_squat_rear_foot_elevated_bodyweight',
    name: 'Bulgarian Split Squat (Bodyweight)',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core', 'hamstrings'],
    equipment: ['bench'],
    role: 'main lift',
    ramp_style: 'accessory',
    default_rest_seconds: 90,
  },
  split_squat_bodyweight: {
    id: 'split_squat_bodyweight',
    name: 'Split Squat (Bodyweight)',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core'],
    equipment: [],
    role: 'main lift',
    ramp_style: 'accessory',
    default_rest_seconds: 90,
  },
  front_squat_moderate: {
    id: 'front_squat_moderate',
    name: 'Front Squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core'],
    equipment: ['barbell', 'rack'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },
  heel_elevated_barbell_back_squat: {
    id: 'heel_elevated_barbell_back_squat',
    name: 'Heel-Elevated Back Squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core'],
    equipment: ['barbell', 'rack', 'plates'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },
  back_squat: {
    id: 'back_squat',
    name: 'Back Squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core', 'hamstrings'],
    equipment: ['barbell', 'rack'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },
  back_squat_moderate_load: {
    id: 'back_squat_moderate_load',
    name: 'Back Squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core', 'hamstrings'],
    equipment: ['barbell', 'rack'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },
  front_squat: {
    id: 'front_squat',
    name: 'Front Squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core'],
    equipment: ['barbell', 'rack'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },
  leg_press_narrow_rom: {
    id: 'leg_press_narrow_rom',
    name: 'Leg Press (Partial ROM)',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: [],
    equipment: ['leg_press_machine'],
    role: 'main lift',
    ramp_style: 'accessory',
    default_rest_seconds: 120,
  },
  reverse_lunge_loaded: {
    id: 'reverse_lunge_loaded',
    name: 'Loaded Reverse Lunge',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings', 'core'],
    equipment: ['dumbbell'],
    role: 'main lift',
    ramp_style: 'accessory',
    default_rest_seconds: 120,
  },
  split_squat_loaded: {
    id: 'split_squat_loaded',
    name: 'Loaded Split Squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['core'],
    equipment: ['dumbbell'],
    role: 'main lift',
    ramp_style: 'accessory',
    default_rest_seconds: 90,
  },
  bulgarian_split_squat_loaded: {
    id: 'bulgarian_split_squat_loaded',
    name: 'Loaded Bulgarian Split Squat',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings', 'core'],
    equipment: ['dumbbell', 'bench'],
    role: 'main lift',
    ramp_style: 'accessory',
    default_rest_seconds: 120,
  },
  forward_lunge_loaded: {
    id: 'forward_lunge_loaded',
    name: 'Loaded Forward Lunge',
    primary_muscles: ['quads', 'glutes'],
    secondary_muscles: ['hamstrings', 'core'],
    equipment: ['dumbbell'],
    role: 'main lift',
    ramp_style: 'accessory',
    default_rest_seconds: 120,
  },

  // ── Hinge pattern ────────────────────────────────────────────────────
  trap_bar_deadlift_light: {
    id: 'trap_bar_deadlift_light',
    name: 'Trap Bar Deadlift (Light)',
    primary_muscles: ['hamstrings', 'glutes', 'back'],
    secondary_muscles: ['core', 'quads'],
    equipment: ['trap_bar', 'plates'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },
  trap_bar_deadlift_moderate: {
    id: 'trap_bar_deadlift_moderate',
    name: 'Trap Bar Deadlift',
    primary_muscles: ['hamstrings', 'glutes', 'back'],
    secondary_muscles: ['core', 'quads'],
    equipment: ['trap_bar', 'plates'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },
  kettlebell_hip_hinge: {
    id: 'kettlebell_hip_hinge',
    name: 'Kettlebell Hip Hinge',
    primary_muscles: ['hamstrings', 'glutes'],
    secondary_muscles: ['back', 'core'],
    equipment: ['kettlebell'],
    role: 'main lift',
    ramp_style: 'accessory',
    default_rest_seconds: 90,
  },
  romanian_deadlift_light: {
    id: 'romanian_deadlift_light',
    name: 'Romanian Deadlift (Light)',
    primary_muscles: ['hamstrings', 'glutes'],
    secondary_muscles: ['back', 'core'],
    equipment: ['barbell', 'plates'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 120,
  },
  romanian_deadlift_moderate: {
    id: 'romanian_deadlift_moderate',
    name: 'Romanian Deadlift',
    primary_muscles: ['hamstrings', 'glutes'],
    secondary_muscles: ['back', 'core'],
    equipment: ['barbell', 'plates'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 150,
  },
  conventional_deadlift_moderate: {
    id: 'conventional_deadlift_moderate',
    name: 'Conventional Deadlift',
    primary_muscles: ['hamstrings', 'glutes', 'back'],
    secondary_muscles: ['core', 'quads'],
    equipment: ['barbell', 'plates'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 240,
  },

  // ── Pressing ────────────────────────────────────────────────────────
  landmine_press: {
    id: 'landmine_press',
    name: 'Landmine Press',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['triceps', 'chest', 'core'],
    equipment: ['barbell', 'landmine'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 120,
  },
  incline_dumbbell_press_neutral_grip: {
    id: 'incline_dumbbell_press_neutral_grip',
    name: 'Incline Neutral-Grip DB Press',
    primary_muscles: ['chest', 'shoulders'],
    secondary_muscles: ['triceps'],
    equipment: ['dumbbell', 'bench'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 120,
  },
  dumbbell_shoulder_press_neutral_grip: {
    id: 'dumbbell_shoulder_press_neutral_grip',
    name: 'Neutral-Grip DB Shoulder Press',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['triceps', 'core'],
    equipment: ['dumbbell'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 120,
  },
  incline_dumbbell_press: {
    id: 'incline_dumbbell_press',
    name: 'Incline Dumbbell Press',
    primary_muscles: ['chest', 'shoulders'],
    secondary_muscles: ['triceps'],
    equipment: ['dumbbell', 'bench'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 120,
  },
  overhead_dumbbell_press: {
    id: 'overhead_dumbbell_press',
    name: 'Overhead Dumbbell Press',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['triceps', 'core'],
    equipment: ['dumbbell'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 120,
  },
  overhead_barbell_press_moderate: {
    id: 'overhead_barbell_press_moderate',
    name: 'Overhead Press',
    primary_muscles: ['shoulders'],
    secondary_muscles: ['triceps', 'core'],
    equipment: ['barbell'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },
  bench_press_moderate: {
    id: 'bench_press_moderate',
    name: 'Bench Press',
    primary_muscles: ['chest', 'shoulders', 'triceps'],
    secondary_muscles: [],
    equipment: ['barbell', 'bench'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },
  bench_press_close_grip_paused: {
    id: 'bench_press_close_grip_paused',
    name: 'Close-Grip Paused Bench Press',
    primary_muscles: ['chest', 'triceps'],
    secondary_muscles: ['shoulders'],
    equipment: ['barbell', 'bench'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 180,
  },

  // ── Pulling ─────────────────────────────────────────────────────────
  cable_row_neutral: {
    id: 'cable_row_neutral',
    name: 'Neutral-Grip Cable Row',
    primary_muscles: ['back'],
    secondary_muscles: ['biceps'],
    equipment: ['cable_machine'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 90,
  },
  chest_supported_row: {
    id: 'chest_supported_row',
    name: 'Chest-Supported Row',
    primary_muscles: ['back'],
    secondary_muscles: ['biceps'],
    equipment: ['dumbbell', 'bench'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 90,
  },
  seated_cable_row: {
    id: 'seated_cable_row',
    name: 'Seated Cable Row',
    primary_muscles: ['back'],
    secondary_muscles: ['biceps'],
    equipment: ['cable_machine'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 90,
  },
  pullup_full: {
    id: 'pullup_full',
    name: 'Pull-Up',
    primary_muscles: ['back', 'biceps'],
    secondary_muscles: ['core'],
    equipment: ['pullup_bar'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 150,
  },
  neutral_grip_pullup_assisted: {
    id: 'neutral_grip_pullup_assisted',
    name: 'Assisted Neutral-Grip Pull-Up',
    primary_muscles: ['back', 'biceps'],
    secondary_muscles: ['core'],
    equipment: ['pullup_bar', 'band'],
    role: 'main lift',
    ramp_style: 'compound',
    default_rest_seconds: 120,
  },
}

// Accessory pool — prioritized from per_session_accessories entries.
export const ACCESSORY_VARIANTS: Record<string, VariantSpec> = {
  seated_leg_curl: {
    id: 'seated_leg_curl',
    name: 'Seated Leg Curl',
    primary_muscles: ['hamstrings'],
    secondary_muscles: [],
    equipment: ['leg_curl_machine'],
    role: 'isolation',
    ramp_style: 'accessory',
    default_rest_seconds: 75,
  },
  hip_abduction_machine: {
    id: 'hip_abduction_machine',
    name: 'Hip Abduction Machine',
    primary_muscles: ['glutes'],
    secondary_muscles: [],
    equipment: ['hip_abduction_machine'],
    role: 'isolation',
    ramp_style: 'accessory',
    default_rest_seconds: 60,
  },
  banded_clamshell: {
    id: 'banded_clamshell',
    name: 'Banded Clamshell',
    primary_muscles: ['glutes'],
    secondary_muscles: [],
    equipment: ['band'],
    role: 'isolation',
    ramp_style: 'none',
    default_rest_seconds: 45,
  },
  vmo_terminal_knee_extension: {
    id: 'vmo_terminal_knee_extension',
    name: 'Banded Terminal Knee Extension',
    primary_muscles: ['quads'],
    secondary_muscles: [],
    equipment: ['band'],
    role: 'rehab',
    ramp_style: 'none',
    default_rest_seconds: 60,
  },
  glute_max_bridge_or_hip_thrust: {
    id: 'glute_max_bridge_or_hip_thrust',
    name: 'Barbell Hip Thrust',
    primary_muscles: ['glutes'],
    secondary_muscles: ['hamstrings', 'core'],
    equipment: ['barbell', 'bench'],
    role: 'accessory',
    library_id: 'ex-hip-thrust',
    ramp_style: 'accessory',
    default_rest_seconds: 90,
  },
  nordic_hamstring_curl: {
    id: 'nordic_hamstring_curl',
    name: 'Nordic Hamstring Curl',
    primary_muscles: ['hamstrings'],
    secondary_muscles: [],
    equipment: [],
    role: 'isolation',
    ramp_style: 'none',
    default_rest_seconds: 90,
  },
  face_pull: {
    id: 'face_pull',
    name: 'Face Pull',
    primary_muscles: ['shoulders', 'back'],
    secondary_muscles: [],
    equipment: ['cable_machine', 'rope'],
    role: 'accessory',
    ramp_style: 'accessory',
    default_rest_seconds: 60,
  },
  prone_y_raise: {
    id: 'prone_y_raise',
    name: 'Prone Y Raise',
    primary_muscles: ['back', 'shoulders'],
    secondary_muscles: [],
    equipment: ['dumbbell'],
    role: 'isolation',
    ramp_style: 'none',
    default_rest_seconds: 45,
  },
  lying_leg_pullover: {
    id: 'lying_leg_pullover',
    name: 'Lying Leg Pullover (Decompression)',
    primary_muscles: ['core'],
    secondary_muscles: ['back'],
    equipment: ['bench'],
    role: 'mobility',
    ramp_style: 'none',
    default_rest_seconds: 30,
  },
  doorway_pec_stretch: {
    id: 'doorway_pec_stretch',
    name: 'Doorway Pec Stretch',
    primary_muscles: ['mobility'],
    secondary_muscles: [],
    equipment: [],
    role: 'mobility',
    ramp_style: 'none',
    default_rest_seconds: 0,
  },
}

// Lookup helper — consult both pools.
export function resolveVariant(id: string): VariantSpec | null {
  return MAIN_VARIANTS[id] ?? ACCESSORY_VARIANTS[id] ?? null
}
